### ISSUE TITLE
setting global parameters

### ISSUE THREAD

**Issue by eliaharm** [RobertoLangarica/quasar-app-extension-api-wrapper#1]
Hello,
This is a nice utility. I wish there was some example on how to use it globally.
I was trying to set Global Configuration but it wasn't clear to me in which file to put theme.
I tried `src\main\webapp\quasar.extensions.json` with the following ( the "api-wrapper" was created automatically I don't know what for):
```javascript
{
  "api-wrapper": {
    "baseURL" : "http://localhost:8080/api/v1/"
  }
}
```
that didn't work...

also as a boot file
```javascript
// import something here

// "async" is optional;
// more info on params: https://quasar.dev/quasar-cli/boot-files
// export default async (/* { app, router, Vue ... } */) => {
export default async ({ app, router, store, Vue }) => {
  // something to do

  console.log('boot api-wrapper start')
  // `baseURL` will be prepended to any path provided unless the provided path is absolute.
   this.$api.baseURL = 'http://localhost:8080/api/v1'

  // The amount of attempts a request will make in the case of a timeout before failing completely
  this.$api.maxAttemptsPerCall = 1

  // The amount of concurrent requests that could be executed (when the requests number exceed this amount the requests are enqueue in a waiting mode)
  this.$api.simultaneousCalls = 5

  // Specifies the number of milliseconds before a request times out
  this.$api.timeout = 10000

  // Sets the default headers for 'Content-Type' for each request
  this.$api.setContentType(type = 'application/json')

  // Sets the default authorization header: 'Authorization' for each request
  this.$api.setAuthorization(token, type = 'Bearer')

  // If the store where not provided in the boot phase then it could be passed to the extension using this function
  // This will bring the module 'APIwrapper' available and the extension will start updating its state
  this.$api.setStore(vuex_instance)

  console.log('boot api-wrapper end')
}
```
got the below errors
```
Failed to compile.

./src/boot/api-wrapper-global.js
Module Error (from ./node_modules/eslint-loader/dist/cjs.js):

C:\src\git-repos\l4p-app\src\main\webapp\src\boot\api-wrapper-global.js
  23:28  error  'type' is not defined           no-undef
  26:30  error  'token' is not defined          no-undef
  26:37  error  'type' is not defined           no-undef
  30:22  error  'vuex_instance' is not defined  no-undef

✖ 4 problems (4 errors, 0 warnings)
```

**Comment by RobertoLangarica** [comment]
Hi @eliaharm,

Thanks for the comments and for using the tool. 

I'll try to address both of your comments.

> I was trying to set Global Configuration but it wasn't clear to me in which file to put theme.
I tried `src\main\webapp\quasar.extensions.json` with the following ( the "api-wrapper" was created automatically I don't know what for)

That `api-wrapper` object is created automatically by quasar when you add the extension (the same happens for every extension) and it saves any configuration made during the installation process. I think it is a good idea to use this as a global configuration, I'll look into it and put it on my roadmap.


**For the second thing that you mentioned using the bootfile**
I think that's a good approach for initialization but I have a couple of observations in order to solve your issues.

The use of `this` in that file is an error since it is not on any context where the `$api` property would exists. The `$api` object exists whenever you are dealing with a vue file, so if you are inside any Vue component `this.$api` will work the same way `this.$store` will do (I'll add this clarification to the documentation to avoid further confusion on that matter). 

**You have 2 options to make it work:**
1. Move the code as you have it to any vue component, App.vue could be a good place for initialization
1. Stick to the bootfile (I prefer this option) but change the access, instead of `this.$api` use only 'api' but you need to import the `api` object. Here is your example with the changes (I already test it in a project and it worked):

```
import api from "api-client-wrapper"

export default async ({ app, router, store, Vue }) => {

    console.log("boot api-wrapper start")

    api.baseURL = "http://localhost:8080/api/v1"
    api.maxAttemptsPerCall = 1
    api.simultaneousCalls = 5
    api.timeout = 10000

    let type = "application/json"
    api.setContentType(type)

    let token = "any obtained token"
    api.setAuthorization(token, "Bearer")

    // If the store where not provided in the boot phase then it could be passed to the extension using this function
    // This will bring the module "APIwrapper" available and the extension will start updating its state
    let vuex_instance
    vuex_instance = /*A valid vuex instance*/
    api.setStore(vuex_instance)
    console.log("boot api-wrapper end")


}
```

**Regarding the errors you mentioned:**

```
Failed to compile.

./src/boot/api-wrapper-global.js
Module Error (from ./node_modules/eslint-loader/dist/cjs.js):

C:\src\git-repos\l4p-app\src\main\webapp\src\boot\api-wrapper-global.js
  23:28  error  'type' is not defined           no-undef
  26:30  error  'token' is not defined          no-undef
  26:37  error  'type' is not defined           no-undef
  30:22  error  'vuex_instance' is not defined  no-undef

✖ 4 problems (4 errors, 0 warnings)
```

The above errors are not related with the extension or the package api-wrapper. The code in the docs showed the functions signatures only, but you need to provide actual values and none of the mentioned variables are defined, so that is why you are getting the errors. If you observe the code that I pasted before you could see that I'm fixing that.
